language: python
python:
  - "3.8"
env:
  - DJANGO_VERSION=3.0.7
install:
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
  - pip install .
virtualenv:
  system_site_packages: true  
